import { Portfolio } from './types';
import { SiAdobeaftereffects, SiAdobeillustrator, SiAdobephotoshop, SiAngular, SiIonic } from 'react-icons/si';

export const portfolio: Portfolio[] = [
    {
        id: 50,
        imageUri: 'https://i.imgur.com/tZH8zI2.png',
        type: 'img',
        title: 'APSpace Web App',
        icons: [SiIonic, SiAngular],
        route: 'sdf',
        tag: ['all', 'app'],
    },
    {
        id: 1,
        imageUri: 'https://res.cloudinary.com/tahmid-rahman/image/upload/v1608366391/connect-software/port-81_xjkomw.png',
        type: 'img',
        title: 'Connect Software Brand Identity',
        icons: [SiAdobeillustrator, SiAdobephotoshop],
        route: 'sdf',
        tag: ['all', 'logo', 'brand identity', 'logo process', 'mockup', 'business card', 'banner & poster'],
    },
    {
        id: 47,
        imageUri: 'https://i.imgur.com/mbGHREH.mp4',
        type: 'vid',
        title: '909 animation',
        icons: [SiAdobeaftereffects],
        route: 'sdf',
        tag: ['all', 'logo', 'brand identity', 'animation'],
    },
    {
        id: 48,
        imageUri: 'https://i.imgur.com/rAsWg4B.mp4',
        type: 'vid',
        title: 'Curiosity',
        icons: [SiAdobeillustrator, SiAdobeaftereffects],
        route: 'sdf',
        tag: ['all', 'animation', 'creatives'],
    },
    {
        id: 49,
        imageUri: 'https://i.imgur.com/ejij1Ma.jpg',
        type: 'img',
        title: 'Balloon Dog',
        icons: [SiAdobeillustrator],
        route: 'sdf',
        tag: ['all', 'creatives', 'banner & poster'],
    },
    {
        id: 2,
        imageUri: 'https://res.cloudinary.com/tahmid-rahman/image/upload/v1608366434/portfolio/port-73_k5vuqv.png',
        type: 'img',
        title: 'Oak Furniture',
        icons: [SiAdobephotoshop],
        route: 'sdf',
        tag: ['all', 'creatives', 'banner & poster', 'mockup'],
    },
    {
        id: 3,
        imageUri: 'https://res.cloudinary.com/tahmid-rahman/image/upload/v1597231163/portfolio/port-74_dgcncl.png',
        type: 'img',
        title: 'Oak Logo',
        icons: [SiAdobeillustrator],
        route: 'sdf',
        tag: ['all', 'logo'],
    },
    {
        id: 7,
        imageUri: 'https://res.cloudinary.com/tahmid-rahman/image/upload/v1597231162/portfolio/port-68_mgznjx.jpg',
        type: 'img',
        title: 'DIY Content',
        icons: [SiAdobephotoshop],
        route: 'sdf',
        tag: ['all', 'creatives'],
    },
    {
        id: 5,
        imageUri: 'https://res.cloudinary.com/tahmid-rahman/image/upload/v1608366434/portfolio/port-72_yj7d4j.png',
        type: 'img',
        title: 'TR Biz Card',
        icons: [SiAdobephotoshop],
        route: 'sdf',
        tag: ['all', 'business card', 'mockup'],
    },
    {
        id: 32,
        imageUri: 'https://i.imgur.com/HkpnWcTh.jpg',
        type: 'img',
        title: 'Maze',
        icons: [SiAdobeillustrator],
        route: 'sdf',
        tag: ['all', 'logo'],
    },
    {
        id: 6,
        imageUri: 'https://res.cloudinary.com/tahmid-rahman/image/upload/v1597231162/portfolio/port-66_myfh5y.jpg',
        type: 'img',
        title: 'Unity Artwork',
        icons: [],
        route: 'sdf',
        tag: ['all', 'art'],
    },
    {
        id: 4,
        imageUri: 'https://res.cloudinary.com/tahmid-rahman/image/upload/v1608366435/portfolio/port-75_i7adtd.png',
        type: 'img',
        title: 'Safepad Creative',
        icons: [],
        route: 'sdf',
        tag: ['all', 'creatives', 'banner & poster', 'mockup'],
    },
    {
        id: 8,
        imageUri: 'https://res.cloudinary.com/tahmid-rahman/image/upload/v1597231161/portfolio/port-65_eaiiro.jpg',
        type: 'img',
        title: 'Suicide Squad Illustration',
        icons: [],
        route: 'sdf',
        tag: ['all', 'banner & poster', 'creatives'],
    },
    {
        id: 9,
        imageUri: 'https://res.cloudinary.com/tahmid-rahman/image/upload/v1597231162/portfolio/port-61_b2vclk.png',
        type: 'img',
        title: 'KTC Poster',
        icons: [],
        route: 'sdf',
        tag: ['all', 'creatives', 'banner & poster'],
    },
    {
        id: 9,
        imageUri: 'https://res.cloudinary.com/tahmid-rahman/image/upload/v1597231160/portfolio/port-55_kfe7ni.jpg',
        type: 'img',
        title: 'PCP Creative',
        icons: [],
        route: 'sdf',
        tag: ['all', 'creatives'],
    },
    {
        id: 10,
        imageUri: 'https://res.cloudinary.com/tahmid-rahman/image/upload/v1597231160/portfolio/port-56_bobskj.jpg',
        type: 'img',
        title: 'Meghrodru Content',
        icons: [],
        route: 'sdf',
        tag: ['all', 'creatives'],
    },
    {
        id: 11,
        imageUri: 'https://res.cloudinary.com/tahmid-rahman/image/upload/v1597231167/portfolio/port-78_gvuzpf.jpg',
        type: 'img',
        title: 'Emotions Artwork',
        icons: [],
        route: 'sdf',
        tag: ['all', 'art'],
    },
    {
        id: 12,
        imageUri: 'https://res.cloudinary.com/tahmid-rahman/image/upload/v1597231159/portfolio/port-49_qw8b6s.jpg',
        type: 'img',
        title: 'Quiver Coffee Branding',
        icons: [],
        route: 'sdf',
        tag: ['all', 'creatives', 'mockup', 'brand identity'],
    },
    {
        id: 13,
        imageUri: 'https://res.cloudinary.com/tahmid-rahman/image/upload/v1597231161/portfolio/port-59_rg8c3g.jpg',
        type: 'img',
        title: 'CRAYZ Creative',
        icons: [],
        route: 'sdf',
        tag: ['all', 'creatives'],
    },
    {
        id: 14,
        imageUri: 'https://res.cloudinary.com/tahmid-rahman/image/upload/v1597231160/portfolio/port-53_mli4xo.jpg',
        type: 'img',
        title: 'Gym wall design',
        icons: [],
        route: 'sdf',
        tag: ['all', 'banner & poster'],
    },
    {
        id: 15,
        imageUri: 'https://res.cloudinary.com/tahmid-rahman/image/upload/v1597231161/portfolio/port-63_wmoxcb.jpg',
        type: 'img',
        title: 'Voice Magazine Cover',
        icons: [],
        route: 'sdf',
        tag: ['all', 'creatives', 'banner & poster'],
    },
    {
        id: 16,
        imageUri: 'https://res.cloudinary.com/tahmid-rahman/image/upload/v1597231161/portfolio/port-62_snqcw9.jpg',
        type: 'img',
        title: 'PCP Banner Design',
        icons: [],
        route: 'sdf',
        tag: ['all', 'banner & poster'],
    },
    {
        id: 17,
        imageUri: 'https://res.cloudinary.com/tahmid-rahman/image/upload/v1597231161/portfolio/port-58_zy9jzn.jpg',
        type: 'img',
        title: 'YV Content Design',
        icons: [],
        route: 'sdf',
        tag: ['all', 'creatives'],
    },
    {
        id: 18,
        imageUri: 'https://res.cloudinary.com/tahmid-rahman/image/upload/v1597231160/portfolio/port-54_nw5wda.jpg',
        type: 'img',
        title: 'Eid Content',
        icons: [],
        route: 'sdf',
        tag: ['all', 'creatives'],
    },
    {
        id: 19,
        imageUri: 'https://res.cloudinary.com/tahmid-rahman/image/upload/v1597231163/portfolio/port-67_jyqriu.jpg',
        type: 'img',
        title: 'CIU Mural',
        icons: [],
        route: 'sdf',
        tag: ['all', 'art'],
    },
    {
        id: 20,
        imageUri: 'https://res.cloudinary.com/tahmid-rahman/image/upload/v1597231159/portfolio/port-51_noucko.jpg',
        type: 'img',
        title: 'Madlad Game Studio',
        icons: [],
        route: 'sdf',
        tag: ['all', 'creatives'],
    },
    {
        id: 21,
        imageUri: 'https://res.cloudinary.com/tahmid-rahman/image/upload/v1597231164/portfolio/port-80_ypqsle.png',
        type: 'img',
        title: 'Jonakir Alo Banner',
        icons: [],
        route: 'sdf',
        tag: ['all', 'creatives', 'banner & poster'],
    },
    {
        id: 22,
        imageUri: 'https://res.cloudinary.com/tahmid-rahman/image/upload/v1597231159/portfolio/port-48_zpoxrv.jpg',
        type: 'img',
        title: 'E2M Catalogue',
        icons: [],
        route: 'sdf',
        tag: ['all', 'creatives', 'mockup', 'brand identity'],
    },
    {
        id: 23,
        imageUri: 'https://res.cloudinary.com/tahmid-rahman/image/upload/v1597231165/portfolio/port-79_wl2ike.jpg',
        type: 'img',
        title: 'lost in dreams artwork',
        icons: [],
        route: 'sdf',
        tag: ['all', 'art'],
    },
    {
        id: 24,
        imageUri: 'https://res.cloudinary.com/tahmid-rahman/image/upload/v1597231158/portfolio/port-44_xgwqla.jpg',
        type: 'img',
        title: 'DIY Creative',
        icons: [],
        route: 'sdf',
        tag: ['all', 'creatives'],
    },
    {
        id: 25,
        imageUri: 'https://res.cloudinary.com/tahmid-rahman/image/upload/v1597231164/portfolio/port-80_ypqsle.png',
        type: 'img',
        title: 'Jonakir Alo Banner',
        icons: [],
        route: 'sdf',
        tag: ['all', 'creatives', 'banner & poster'],
    },
    {
        id: 26,
        imageUri: 'https://res.cloudinary.com/tahmid-rahman/image/upload/v1597231158/portfolio/port-41_nphacr.jpg',
        type: 'img',
        title: 'DIY Logo',
        icons: [],
        route: 'sdf',
        tag: ['all', 'creatives', 'banner & poster'],
    },
    {
        id: 27,
        imageUri: 'https://res.cloudinary.com/tahmid-rahman/image/upload/v1597231159/portfolio/port-50_lihldh.jpg',
        type: 'img',
        title: 'Bangladesh Independence Day Content',
        icons: [],
        route: 'sdf',
        tag: ['all', 'creatives'],
    },
    {
        id: 28,
        imageUri: 'https://res.cloudinary.com/tahmid-rahman/image/upload/v1597231158/portfolio/port-40_jfc4eq.jpg',
        type: 'img',
        title: 'Synaptic',
        icons: [],
        route: 'sdf',
        tag: ['all', 'logo'],
    },
    {
        id: 29,
        imageUri: 'https://res.cloudinary.com/tahmid-rahman/image/upload/v1597231158/portfolio/port-39_oqw0fx.jpg',
        type: 'img',
        title: 'The PR',
        icons: [],
        route: 'sdf',
        tag: ['all', 'logo'],
    },
    {
        id: 30,
        imageUri: 'https://res.cloudinary.com/tahmid-rahman/image/upload/v1597231158/portfolio/port-38_l2czix.jpg',
        type: 'img',
        title: 'Taranga Courtyard',
        icons: [],
        route: 'sdf',
        tag: ['all', 'logo'],
    },
    {
        id: 31,
        imageUri: 'https://res.cloudinary.com/tahmid-rahman/image/upload/v1597231158/portfolio/port-37_te6x2t.jpg',
        type: 'img',
        title: 'Margin Tag',
        icons: [],
        route: 'sdf',
        tag: ['all', 'mockup'],
    },
    {
        id: 33,
        imageUri: 'https://res.cloudinary.com/tahmid-rahman/image/upload/v1597231157/portfolio/port-32_dpsjec.jpg',
        type: 'img',
        title: 'SafePad Package Design',
        icons: [],
        route: 'sdf',
        tag: ['all', 'mockup'],
    },
    {
        id: 34,
        imageUri: 'https://res.cloudinary.com/tahmid-rahman/image/upload/v1597231158/portfolio/port-34_rqccgk.jpg',
        type: 'img',
        title: 'Core Water Bottle',
        icons: [],
        route: 'sdf',
        tag: ['all', 'mockup'],
    },
    {
        id: 35,
        imageUri: 'https://res.cloudinary.com/tahmid-rahman/image/upload/v1597231157/portfolio/port-33_q7j4ik.jpg',
        type: 'img',
        title: 'Core',
        icons: [],
        route: 'sdf',
        tag: ['all', 'logo'],
    },
    {
        id: 36,
        imageUri: 'https://res.cloudinary.com/tahmid-rahman/image/upload/v1597231157/portfolio/port-31_rw1ryg.jpg',
        type: 'img',
        title: 'Hustle Hut',
        icons: [],
        route: 'sdf',
        tag: ['all', 'logo', 'brand identity'],
    },
    {
        id: 37,
        imageUri: 'https://res.cloudinary.com/tahmid-rahman/image/upload/v1597231157/portfolio/port-30_n6od23.jpg',
        type: 'img',
        title: 'Florida Tulip Content',
        icons: [],
        route: 'sdf',
        tag: ['all', 'creatives'],
    },
    {
        id: 38,
        imageUri: 'https://res.cloudinary.com/tahmid-rahman/image/upload/v1597231157/portfolio/port-29_cnkg3d.jpg',
        type: 'img',
        title: 'Florida Tulip Magazine',
        icons: [],
        route: 'sdf',
        tag: ['all', 'creatives', 'mockup'],
    },
    {
        id: 39,
        imageUri: 'https://res.cloudinary.com/tahmid-rahman/image/upload/v1597231157/portfolio/port-28_tu5xxc.jpg',
        type: 'img',
        title: 'Florida Tulip',
        icons: [],
        route: 'sdf',
        tag: ['all', 'logo', 'mockup'],
    },
    {
        id: 40,
        imageUri: 'https://res.cloudinary.com/tahmid-rahman/image/upload/v1597231157/portfolio/port-26_luiojt.jpg',
        type: 'img',
        title: 'Deluxe City Mockup',
        icons: [],
        route: 'sdf',
        tag: ['all', 'mockup'],
    },
    {
        id: 41,
        imageUri: 'https://res.cloudinary.com/tahmid-rahman/image/upload/v1597231156/portfolio/port-22_q4wchx.jpg',
        type: 'img',
        title: 'Occult',
        icons: [],
        route: 'sdf',
        tag: ['all', 'logo', 'brand identity'],
    },
    {
        id: 42,
        imageUri: 'https://res.cloudinary.com/tahmid-rahman/image/upload/v1597231156/portfolio/port-20_etjfcw.jpg',
        type: 'img',
        title: 'Ghost Mockup',
        icons: [],
        route: 'sdf',
        tag: ['all', 'mockup'],
    },
    {
        id: 43,
        imageUri: 'https://res.cloudinary.com/tahmid-rahman/image/upload/v1597231156/portfolio/port-17_chghv9.jpg',
        type: 'img',
        title: 'Peacock',
        icons: [],
        route: 'sdf',
        tag: ['all', 'logo', 'brand identity'],
    },
    {
        id: 44,
        imageUri: 'https://res.cloudinary.com/tahmid-rahman/image/upload/v1597231155/portfolio/port-16_esn0fm.jpg',
        type: 'img',
        title: 'Peacock Logo Process',
        icons: [],
        route: 'sdf',
        tag: ['all', 'logo'],
    },
    {
        id: 45,
        imageUri: 'https://res.cloudinary.com/tahmid-rahman/image/upload/v1597231155/portfolio/port-12_mrqqrj.jpg',
        type: 'img',
        title: 'Doge',
        icons: [],
        route: 'sdf',
        tag: ['all', 'logo'],
    },
    {
        id: 46,
        imageUri: 'https://res.cloudinary.com/tahmid-rahman/image/upload/v1597231154/portfolio/port-1_kahvan.jpg',
        type: 'img',
        title: 'Youth Worldwide Foundation',
        icons: [],
        route: 'sdf',
        tag: ['all', 'logo'],
    },
]
